[13.0][ADD] base_module_remove_batch
solvosci/slv-server pull request #1
Opened 2021-03-16 11:12 UTC by ChristianSantamaria

Adds option to remove modules in batch.

2021-03-16 11:26 UTC, dalonsod requested changes
Only code review, see comments. Also,
- is it possible to fire an error if there's no uninstallable addons in the selection?
- re-thinking about addon naming (I'm sorry, but this name was suggested by me), now I've changed opinion: a better name should be `base_module_uninstall_batch`, because we're trying to uninstall modules, not removing them from Odoo bdd. Other possibility is adding another action "Uninstall and remove modules"; then, the current module name could be preserved. What do you think about it?

2021-03-16 11:26 UTC, dalonsod commented on base_module_remove_batch/__manifest__.py
> +    "version": "12.0.2.1.0",
Wrong version

2021-03-16 11:26 UTC, dalonsod commented on base_module_remove_batch/__manifest__.py
> +    "website": "https://github.com/solvosci/slv-helpdesk",
Wrong website

2021-03-16 11:26 UTC, dalonsod commented on base_module_remove_batch/__manifest__.py
> +# © 2020 Solvos Consultoría Informática (<http://www.solvos.es>)
Wrong year

2021-03-16 11:26 UTC, dalonsod commented on base_module_remove_batch/__manifest__.py
> +        "data/ir_action_data.xml",
I'm not sure if data such as a server action should be placed in a `data` folder. `data` folder is often used for master initialization data. Maybe a server action should be treated like other structures (views, menus, client actions,...) that are placed under `views` folder instead.

2021-03-16 13:19 UTC, dalonsod commented on base_module_remove_batch/__manifest__.py
> +    "version": "12.0.2.1.0",
Still wrong version... this addon is for v13, isn't it?

2021-03-16 14:44 UTC, ChristianSantamaria commented on base_module_remove_batch/__manifest__.py
> +    "version": "12.0.2.1.0",
Yes, sorry, I had done it in v12 but in v13 it still works

2021-03-17 07:15 UTC, ChristianSantamaria commented
Yes, you are right, it is a more appropriate name if in the future we make it eliminate the modules we will change the name again.

2021-03-17 07:22 UTC, ChristianSantamaria commented
> is it possible to fire an error if there's no uninstallable addons in the selection?

In the event that one or more selected modules are already uninstalled, odoo will show this warning message
![imagen](https://user-images.githubusercontent.com/22427989/111429858-db59b480-86f9-11eb-8541-80e57dc7517a.png)

2021-03-17 09:34 UTC, dalonsod requested changes
Locally tested, LGTM.
Please add `i18n` files, generate the `README.rst` and `index.html` files and squash commits

2021-03-17 09:34 UTC, dalonsod commented on base_module_uninstall_batch/__manifest__.py
> +    "version": "13.0.0.1.0",
Wrong version
```suggestion
    "version": "13.0.1.0.0",
```

2021-03-17 11:55 UTC, dalonsod approved these changes
LGTM

2021-03-17 11:56 UTC, dalonsod commented
In a future version we could add a second button called "Uninstall & remove", but it's not mandatory for now. Merging...

2021-03-17 11:56 UTC, merged